name: Test Suite

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  installer-tests:
    name: Run Installer Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run installer tests
        working-directory: tests/installer
        run: |
          echo "Running installer tests..."
          make test-linux

      - name: Clean up Docker resources
        if: always()
        working-directory: tests/installer
        run: |
          make clean

  # Add this job to act as a required check that depends on all test jobs
  all-tests:
    name: All Tests Passed
    runs-on: ubuntu-latest
    needs: [installer-tests]
    if: always()
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.installer-tests.result }}" != "success" ]]; then
            echo "❌ Tests failed - installer-tests: ${{ needs.installer-tests.result }}"
            exit 1
          fi
          echo "✅ All tests passed successfully!"